# Site settings
title: Prashant Baisla
email: prashantbaisla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about computers, programming and anything else that might interest me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pbaisla.github.io/" # the base hostname & protocol for your site
twitter_username: prashant7b
github_username:  pbaisla

# Build settings
markdown: kramdown
